#!/usr/bin/env bash
# installs nginx and configure it to on a remote server
# nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx
ufw allow "NGINX HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
