#!/usr/bin/env bash
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm

sudo apt-get -y update
apt-get -y install haproxy

# Configuration of HAproxy
server_config=\
"
frontend  vivianne-frontend
        bind *:80
        mode http
        default_backend vivianne-backend
backend vivianne-backend
        balance roundrobin
        server	199821-web-01 34.224.1.159 check
	server	199821-web-02 34.239.254.245 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
