#!/usr/bin/env bash
# script that:
#   Create a file /var/run/myscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/myscript.pid and terminates upon receiving a SIGQUIT or SIGTERM.

trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; sudo rm /var/run/myscript.pid; exit" SIGTERM
trap "sudo rm /var/run/myscript.pid; exit" SIGQUIT

sudo touch /var/run/myscript.pid
i=1
while [ "$i" -eq 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done
