#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.
# and pauses two seconds in between each message.

j=0
while [ "$j" -eq 0 ]
do
	echo "I am alive!" | sudo tee -a /tmp/my_process > /dev/null
	sleep 2
done
