#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd
#script should display username, user id, home directory path for the user

while IFS= read -r line
do
	echo "$line" | cut -d':' --fields=1,3,6
done < /etc/passwd
