#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd

while IFS=: read -r usr pass id gid infor hom comm
do
	echo "The user $usr is part of the $gid gang, lives in $hom and rides $comm. $id's place is protected by the passcode $pass, more info about the user here: $infor"
done < /etc/passwd
