#!/usr/bin/env bash
# Script that displays numbers from 1 to 20 and:
# displays 4 then "bad luck from China" for the 4th iteration
# displays 9 then "bad luck from Japan" for the 9th iteration
# displays 17 then "bad luck from Italy" for the 17th iteration

a=1

while [ $a -le 20 ]
do
	echo "$a"
	case $a in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
	esac
	(( a++ ))
done
